{"name": "test_put_auth[auth_error_header1]", "status": "failed", "statusDetails": {"message": "Failed: API ERROR", "trace": "method = 'PUT', url = 'https://gorest.co.in/public/v2/users/6856184', r_json = {'name': 'Pan', 'status': 'active'}\nheaders = {'Authorization': 'Bearer 18661386073d8ec7e241a5395233b5ce5457a4a7acca76f0a37f0ff14e057a7b1', 'Content-Type': 'application/json'}, status = 200\n\n    def call_api_custom(method, url, r_json = None, headers = None, status = None):\n        response = requests.request(method, url,json = r_json,headers= headers)\n        try:\n>           assert response.status_code == status, f\"API ERROR, status code is {response.status_code}\"\nE           AssertionError: API ERROR, status code is 401\n\ncustom_call.py:6: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\nauth_error_header = {'Authorization': 'Bearer 18661386073d8ec7e241a5395233b5ce5457a4a7acca76f0a37f0ff14e057a7b1', 'Content-Type': 'application/json'}\n\n    def test_put_auth(auth_error_header):\n        global id\n        global id_1\n        global id_2\n        if(auth_error_header == common_utility.get_header_error2()):\n            id_2 = post()\n            id = id_2\n        if(auth_error_header == common_utility.get_header_error1()):\n            id_1 = 6850005\n            id = id_1\n        url = api_url.GET_URL + f\"/{id}\"\n        headers = auth_error_header\n        c_u = file.read_file(\"C:\\\\api-testing\\\\config\\\\update.json\")\n>       response = custom_call.call_api_custom(\"PUT\", url, headers=headers, r_json=c_u, status=200)\n\ntest_script2.py:69: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nmethod = 'PUT', url = 'https://gorest.co.in/public/v2/users/6856184', r_json = {'name': 'Pan', 'status': 'active'}\nheaders = {'Authorization': 'Bearer 18661386073d8ec7e241a5395233b5ce5457a4a7acca76f0a37f0ff14e057a7b1', 'Content-Type': 'application/json'}, status = 200\n\n    def call_api_custom(method, url, r_json = None, headers = None, status = None):\n        response = requests.request(method, url,json = r_json,headers= headers)\n        try:\n            assert response.status_code == status, f\"API ERROR, status code is {response.status_code}\"\n            return response\n        except:\n>           pytest.fail(\"API ERROR\")\nE           Failed: API ERROR\n\ncustom_call.py:9: Failed"}, "parameters": [{"name": "auth_error_header", "value": "{'Content-Type': 'application/json', 'Authorization': 'Bearer 18661386073d8ec7e241a5395233b5ce5457a4a7acca76f0a37f0ff14e057a7b1'}"}], "start": 1713314915451, "stop": 1713314917953, "uuid": "6d0d7ae7-cb09-4d91-ab95-09096d9af942", "historyId": "96b6d4ce8367bec0d97783436d45475f", "testCaseId": "ee63ec88efefe9d3f6e6038da650c3e8", "fullName": "test_script2#test_put_auth", "labels": [{"name": "suite", "value": "test_script2"}, {"name": "host", "value": "HPENVY13"}, {"name": "thread", "value": "16724-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_script2"}]}