{"name": "test_post_auth[auth_error_header1]", "status": "failed", "statusDetails": {"message": "Failed: API ERROR", "trace": "method = 'POST', url = 'https://gorest.co.in/public/v2/users'\nr_json = {'email': 'test_auto_8286@gmail.com', 'gender': 'male', 'name': 'Pankaj G', 'status': 'active'}\nheaders = {'Authorization': 'Bearer 18661386073d8ec7e241a5395233b5ce5457a4a7acca76f0a37f0ff14e057a7b1', 'Content-Type': 'application/json'}, status = 201\n\n    def call_api_custom(method, url, r_json = None, headers = None, status = None):\n        response = requests.request(method, url,json = r_json,headers= headers)\n        try:\n>           assert response.status_code == status, f\"API ERROR, status code is {response.status_code}\"\nE           AssertionError: API ERROR, status code is 401\n\ncustom_call.py:6: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\nauth_error_header = {'Authorization': 'Bearer 18661386073d8ec7e241a5395233b5ce5457a4a7acca76f0a37f0ff14e057a7b1', 'Content-Type': 'application/json'}\n\n    def test_post_auth(auth_error_header):\n        url = api_url.GET_URL\n        headers = auth_error_header\n        c_u = file.read_file(\"C:\\\\api-testing\\\\config\\\\create.json\")\n        c_u[\"email\"] = common_utility.get_email()\n>       response = custom_call.call_api_custom(\"POST\", url, headers=headers, r_json=c_u, status=201)\n\ntest_script2.py:47: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nmethod = 'POST', url = 'https://gorest.co.in/public/v2/users'\nr_json = {'email': 'test_auto_8286@gmail.com', 'gender': 'male', 'name': 'Pankaj G', 'status': 'active'}\nheaders = {'Authorization': 'Bearer 18661386073d8ec7e241a5395233b5ce5457a4a7acca76f0a37f0ff14e057a7b1', 'Content-Type': 'application/json'}, status = 201\n\n    def call_api_custom(method, url, r_json = None, headers = None, status = None):\n        response = requests.request(method, url,json = r_json,headers= headers)\n        try:\n            assert response.status_code == status, f\"API ERROR, status code is {response.status_code}\"\n            return response\n        except:\n>           pytest.fail(\"API ERROR\")\nE           Failed: API ERROR\n\ncustom_call.py:9: Failed"}, "parameters": [{"name": "auth_error_header", "value": "{'Content-Type': 'application/json', 'Authorization': 'Bearer 18661386073d8ec7e241a5395233b5ce5457a4a7acca76f0a37f0ff14e057a7b1'}"}], "start": 1713314912075, "stop": 1713314913984, "uuid": "ce6e766d-bdc4-45f2-b7be-e4945f5ac7f7", "historyId": "0f384c3161da00c62ab7a642c1d9f300", "testCaseId": "fb3adcf9b5200396b9d018b8c9ce9680", "fullName": "test_script2#test_post_auth", "labels": [{"name": "suite", "value": "test_script2"}, {"name": "host", "value": "HPENVY13"}, {"name": "thread", "value": "16724-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_script2"}]}