{"name": "test_get_auth[auth_error_header1]", "status": "failed", "statusDetails": {"message": "Failed: API ERROR", "trace": "method = 'GET', url = 'https://gorest.co.in/public/v2/users', r_json = None\nheaders = {'Authorization': 'Bearer 18661386073d8ec7e241a5395233b5ce5457a4a7acca76f0a37f0ff14e057a7b1', 'Content-Type': 'application/json'}, status = 200\n\n    def call_api_custom(method, url, r_json = None, headers = None, status = None):\n        response = requests.request(method, url,json = r_json,headers= headers)\n        try:\n>           assert response.status_code == status, f\"API ERROR, status code is {response.status_code}\"\nE           AssertionError: API ERROR, status code is 401\n\ncustom_call.py:6: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\nauth_error_header = {'Authorization': 'Bearer 18661386073d8ec7e241a5395233b5ce5457a4a7acca76f0a37f0ff14e057a7b1', 'Content-Type': 'application/json'}\n\n    def test_get_auth(auth_error_header):\n        url = api_url.GET_URL\n        headers = auth_error_header\n>       response = custom_call.call_api_custom(\"GET\", url, headers=headers, status=200)\n\ntest_script2.py:36: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nmethod = 'GET', url = 'https://gorest.co.in/public/v2/users', r_json = None\nheaders = {'Authorization': 'Bearer 18661386073d8ec7e241a5395233b5ce5457a4a7acca76f0a37f0ff14e057a7b1', 'Content-Type': 'application/json'}, status = 200\n\n    def call_api_custom(method, url, r_json = None, headers = None, status = None):\n        response = requests.request(method, url,json = r_json,headers= headers)\n        try:\n            assert response.status_code == status, f\"API ERROR, status code is {response.status_code}\"\n            return response\n        except:\n>           pytest.fail(\"API ERROR\")\nE           Failed: API ERROR\n\ncustom_call.py:9: Failed"}, "parameters": [{"name": "auth_error_header", "value": "{'Content-Type': 'application/json', 'Authorization': 'Bearer 18661386073d8ec7e241a5395233b5ce5457a4a7acca76f0a37f0ff14e057a7b1'}"}], "start": 1713314908763, "stop": 1713314910312, "uuid": "d79aa683-564a-400a-a624-7c033f3f7f4e", "historyId": "27c7c2520100dd58c3b38e583da41d46", "testCaseId": "a8c1ed4dde3999f2424b6f329d5db697", "fullName": "test_script2#test_get_auth", "labels": [{"name": "suite", "value": "test_script2"}, {"name": "host", "value": "HPENVY13"}, {"name": "thread", "value": "16724-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_script2"}]}