{"name": "test_delete_auth[auth_error_header0]", "status": "failed", "statusDetails": {"message": "Failed: API ERROR", "trace": "method = 'DELETE', url = 'https://gorest.co.in/public/v2/users/6850005', r_json = None, headers = {'Content-Type': 'application/json'}, status = 204\n\n    def call_api_custom(method, url, r_json = None, headers = None, status = None):\n        response = requests.request(method, url,json = r_json,headers= headers)\n        try:\n>           assert response.status_code == status, f\"API ERROR, status code is {response.status_code}\"\nE           AssertionError: API ERROR, status code is 401\n\ncustom_call.py:6: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\nauth_error_header = {'Content-Type': 'application/json'}\n\n    def test_delete_auth(auth_error_header):\n        global id\n        global id_1\n        global id_2\n        if(auth_error_header == common_utility.get_header_error2()):\n            id = id_2\n        if(auth_error_header == common_utility.get_header_error1()):\n            id = id_1\n        url = api_url.GET_URL + f\"/{id}\"\n        headers = auth_error_header\n>       response = custom_call.call_api_custom(\"DELETE\", url, headers=headers, status=204)\n\ntest_script2.py:85: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nmethod = 'DELETE', url = 'https://gorest.co.in/public/v2/users/6850005', r_json = None, headers = {'Content-Type': 'application/json'}, status = 204\n\n    def call_api_custom(method, url, r_json = None, headers = None, status = None):\n        response = requests.request(method, url,json = r_json,headers= headers)\n        try:\n            assert response.status_code == status, f\"API ERROR, status code is {response.status_code}\"\n            return response\n        except:\n>           pytest.fail(\"API ERROR\")\nE           Failed: API ERROR\n\ncustom_call.py:9: Failed"}, "parameters": [{"name": "auth_error_header", "value": "{'Content-Type': 'application/json'}"}], "start": 1713314917990, "stop": 1713314919264, "uuid": "fb05a32f-f0ac-4a1c-9d65-b88029d98930", "historyId": "9973182d665c9b70651ed1f3f70882ae", "testCaseId": "f485e24547c19276693c5afc6930cf64", "fullName": "test_script2#test_delete_auth", "labels": [{"name": "suite", "value": "test_script2"}, {"name": "host", "value": "HPENVY13"}, {"name": "thread", "value": "16724-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_script2"}]}